// Auto-generated by scripts/generate-card-summary.ts — DO NOT EDIT DIRECTLY
// Lightweight card metadata (no visual-lore, no 5D long interpretations)
// Saves bundle weight when client components only need basic card info

export interface CardSummary {
  id: string;
  name: string;
  nameTh: string;
  nameEn: string;
  image: string;
  arcana: "major" | "minor";
  suit: "wands" | "cups" | "swords" | "pentacles" | null;
  number: number;
  element: string;
  astrology: string;
  keywords: { upright: string[]; reversed: string[] };
}

export const CARD_SUMMARIES: readonly CardSummary[] = [
  {
    "id": "major-00",
    "name": "คนเขลา",
    "nameTh": "คนเขลา",
    "nameEn": "The Fool",
    "image": "major-00.jpg",
    "arcana": "major",
    "suit": null,
    "number": 0,
    "element": "ลม",
    "astrology": "ดาวยูเรนัส",
    "keywords": {
      "upright": [
        "เริ่มต้นใหม่",
        "อิสระ",
        "ไร้เดียงสา",
        "ก้าวกระโดด",
        "ความเป็นไปได้"
      ],
      "reversed": [
        "ประมาท",
        "ลังเล",
        "ไร้ทิศทาง",
        "เสี่ยงเกินตัว"
      ]
    }
  },
  {
    "id": "major-01",
    "name": "นักมายากล",
    "nameTh": "นักมายากล",
    "nameEn": "The Magician",
    "image": "major-01.jpg",
    "arcana": "major",
    "suit": null,
    "number": 1,
    "element": "ลม",
    "astrology": "ดาวพุธ",
    "keywords": {
      "upright": [
        "ลงมือทำ",
        "ความสามารถ",
        "โฟกัส",
        "สื่อสารเก่ง",
        "ทรัพยากรพร้อม"
      ],
      "reversed": [
        "หลอกลวง",
        "พลังกระจัดกระจาย",
        "พูดเกินจริง",
        "ยังไม่ลงมือ"
      ]
    }
  },
  {
    "id": "major-02",
    "name": "นักบวชหญิง",
    "nameTh": "นักบวชหญิง",
    "nameEn": "The High Priestess",
    "image": "major-02.jpg",
    "arcana": "major",
    "suit": null,
    "number": 2,
    "element": "น้ำ",
    "astrology": "ดวงจันทร์",
    "keywords": {
      "upright": [
        "สัญชาตญาณ",
        "ความลับ",
        "เงียบสงบ",
        "รอจังหวะ",
        "ปัญญาภายใน"
      ],
      "reversed": [
        "เก็บงำเกินไป",
        "ไม่ฟังใจตัวเอง",
        "ข้อมูลถูกปิดบัง",
        "สับสน"
      ]
    }
  },
  {
    "id": "major-03",
    "name": "จักรพรรดินี",
    "nameTh": "จักรพรรดินี",
    "nameEn": "The Empress",
    "image": "major-03.jpg",
    "arcana": "major",
    "suit": null,
    "number": 3,
    "element": "ดิน",
    "astrology": "ดาวศุกร์",
    "keywords": {
      "upright": [
        "ความอุดมสมบูรณ์",
        "การดูแล",
        "ความคิดสร้างสรรค์",
        "อ่อนโยน",
        "เติบโต"
      ],
      "reversed": [
        "ให้จนหมดตัว",
        "ละเลยตัวเอง",
        "ยึดติด",
        "หมดไฟสร้างสรรค์"
      ]
    }
  },
  {
    "id": "major-04",
    "name": "จักรพรรดิ",
    "nameTh": "จักรพรรดิ",
    "nameEn": "The Emperor",
    "image": "major-04.jpg",
    "arcana": "major",
    "suit": null,
    "number": 4,
    "element": "ไฟ",
    "astrology": "ราศีเมษ",
    "keywords": {
      "upright": [
        "ความมั่นคง",
        "ระเบียบ",
        "ผู้นำ",
        "กฎเกณฑ์",
        "ควบคุมได้"
      ],
      "reversed": [
        "เข้มงวดเกินไป",
        "ดื้อรั้น",
        "ขาดวินัย",
        "อำนาจกดทับ"
      ]
    }
  },
  {
    "id": "major-05",
    "name": "นักบวช",
    "nameTh": "นักบวช",
    "nameEn": "The Hierophant",
    "image": "major-05.jpg",
    "arcana": "major",
    "suit": null,
    "number": 5,
    "element": "ดิน",
    "astrology": "ราศีพฤษภ",
    "keywords": {
      "upright": [
        "ขนบธรรมเนียม",
        "ครูผู้สอน",
        "ความเชื่อ",
        "คำแนะนำ",
        "ระบบที่พิสูจน์แล้ว"
      ],
      "reversed": [
        "ต่อต้านกรอบ",
        "ตั้งคำถามกับความเชื่อ",
        "ทำตามเขาไปเรื่อย",
        "ยึดตำราเกินไป"
      ]
    }
  },
  {
    "id": "major-06",
    "name": "คู่รัก",
    "nameTh": "คู่รัก",
    "nameEn": "The Lovers",
    "image": "major-06.jpg",
    "arcana": "major",
    "suit": null,
    "number": 6,
    "element": "ลม",
    "astrology": "ราศีเมถุน",
    "keywords": {
      "upright": [
        "ทางเลือก",
        "ความผูกพัน",
        "ความกลมกลืน",
        "ค่านิยมตรงกัน",
        "ตัดสินใจด้วยใจ"
      ],
      "reversed": [
        "ลังเล",
        "ค่านิยมไม่ตรงกัน",
        "เลือกผิดทาง",
        "ความสัมพันธ์ไม่สมดุล"
      ]
    }
  },
  {
    "id": "major-07",
    "name": "ราชรถ",
    "nameTh": "ราชรถ",
    "nameEn": "The Chariot",
    "image": "major-07.jpg",
    "arcana": "major",
    "suit": null,
    "number": 7,
    "element": "น้ำ",
    "astrology": "ราศีกรกฎ",
    "keywords": {
      "upright": [
        "มุ่งมั่น",
        "ชัยชนะ",
        "ควบคุมทิศทาง",
        "เดินหน้า",
        "เอาชนะอุปสรรค"
      ],
      "reversed": [
        "เสียการควบคุม",
        "แรงหมดกลางทาง",
        "ใจร้อน",
        "ไปคนละทิศ"
      ]
    }
  },
  {
    "id": "major-08",
    "name": "พลัง",
    "nameTh": "พลัง",
    "nameEn": "Strength",
    "image": "major-08.jpg",
    "arcana": "major",
    "suit": null,
    "number": 8,
    "element": "ไฟ",
    "astrology": "ราศีสิงห์",
    "keywords": {
      "upright": [
        "ความกล้าจากข้างใน",
        "อดทน",
        "อ่อนโยนแต่หนักแน่น",
        "คุมอารมณ์",
        "เมตตา"
      ],
      "reversed": [
        "หมดแรงใจ",
        "ขาดความมั่นใจ",
        "เก็บกดอารมณ์",
        "ใช้กำลังแก้ปัญหา"
      ]
    }
  },
  {
    "id": "major-09",
    "name": "ฤๅษี",
    "nameTh": "ฤๅษี",
    "nameEn": "The Hermit",
    "image": "major-09.jpg",
    "arcana": "major",
    "suit": null,
    "number": 9,
    "element": "ดิน",
    "astrology": "ราศีกันย์",
    "keywords": {
      "upright": [
        "ทบทวนตัวเอง",
        "ปลีกวิเวก",
        "หาคำตอบข้างใน",
        "ปัญญา",
        "ค่อย ๆ เดิน"
      ],
      "reversed": [
        "โดดเดี่ยวเกินไป",
        "ปิดกั้นคนอื่น",
        "หลงทาง",
        "หนีความจริง"
      ]
    }
  },
  {
    "id": "major-10",
    "name": "กงล้อแห่งโชคชะตา",
    "nameTh": "กงล้อแห่งโชคชะตา",
    "nameEn": "Wheel of Fortune",
    "image": "major-10.jpg",
    "arcana": "major",
    "suit": null,
    "number": 10,
    "element": "ไฟ",
    "astrology": "ดาวพฤหัสบดี",
    "keywords": {
      "upright": [
        "จุดเปลี่ยน",
        "โชคเข้าข้าง",
        "วัฏจักร",
        "จังหวะเวลา",
        "โอกาสหมุนมา"
      ],
      "reversed": [
        "จังหวะไม่เข้า",
        "ติดอยู่ในวงเดิม",
        "ต้านการเปลี่ยนแปลง",
        "รอนานกว่าที่คิด"
      ]
    }
  },
  {
    "id": "major-11",
    "name": "ความยุติธรรม",
    "nameTh": "ความยุติธรรม",
    "nameEn": "Justice",
    "image": "major-11.jpg",
    "arcana": "major",
    "suit": null,
    "number": 11,
    "element": "ลม",
    "astrology": "ราศีตุลย์",
    "keywords": {
      "upright": [
        "ความเป็นธรรม",
        "สมดุล",
        "รับผิดชอบ",
        "ตัดสินใจด้วยเหตุผล",
        "ความจริง"
      ],
      "reversed": [
        "ลำเอียง",
        "หนีความรับผิดชอบ",
        "ตัดสินด้วยอารมณ์",
        "ค้างคา"
      ]
    }
  },
  {
    "id": "major-12",
    "name": "ชายผู้ถูกแขวน",
    "nameTh": "ชายผู้ถูกแขวน",
    "nameEn": "The Hanged Man",
    "image": "major-12.jpg",
    "arcana": "major",
    "suit": null,
    "number": 12,
    "element": "น้ำ",
    "astrology": "ดาวเนปจูน",
    "keywords": {
      "upright": [
        "หยุดรอ",
        "มองมุมใหม่",
        "ยอมปล่อย",
        "เสียสละ",
        "ใจเย็น"
      ],
      "reversed": [
        "ติดอยู่กับที่",
        "ดื้อรั้น",
        "รอเปล่า",
        "เสียสละเกินตัว"
      ]
    }
  },
  {
    "id": "major-13",
    "name": "ความตาย",
    "nameTh": "ความตาย",
    "nameEn": "Death",
    "image": "major-13.jpg",
    "arcana": "major",
    "suit": null,
    "number": 13,
    "element": "น้ำ",
    "astrology": "ราศีพิจิก",
    "keywords": {
      "upright": [
        "จบเพื่อเริ่มใหม่",
        "เปลี่ยนผ่าน",
        "ปล่อยวาง",
        "ลอกคราบ",
        "ปิดบท"
      ],
      "reversed": [
        "ไม่ยอมปล่อย",
        "ยื้อ",
        "กลัวเปลี่ยน",
        "ค้างเติ่ง"
      ]
    }
  },
  {
    "id": "major-14",
    "name": "ความพอดี",
    "nameTh": "ความพอดี",
    "nameEn": "Temperance",
    "image": "major-14.jpg",
    "arcana": "major",
    "suit": null,
    "number": 14,
    "element": "ไฟ",
    "astrology": "ราศีธนู",
    "keywords": {
      "upright": [
        "สมดุล",
        "ค่อยเป็นค่อยไป",
        "ผสมผสาน",
        "ใจเย็น",
        "เยียวยา"
      ],
      "reversed": [
        "เกินพอดี",
        "ใจร้อน",
        "ขาดสมดุล",
        "ฝืนตัวเอง"
      ]
    }
  },
  {
    "id": "major-15",
    "name": "ปีศาจ",
    "nameTh": "ปีศาจ",
    "nameEn": "The Devil",
    "image": "major-15.jpg",
    "arcana": "major",
    "suit": null,
    "number": 15,
    "element": "ดิน",
    "astrology": "ราศีมังกร",
    "keywords": {
      "upright": [
        "ความยึดติด",
        "พันธนาการ",
        "ความอยาก",
        "วนซ้ำ",
        "เห็นแก่ตัวชั่วคราว"
      ],
      "reversed": [
        "เริ่มปลดโซ่",
        "รู้ตัว",
        "ทวงอิสระคืน",
        "ยังลังเล"
      ]
    }
  },
  {
    "id": "major-16",
    "name": "หอคอย",
    "nameTh": "หอคอย",
    "nameEn": "The Tower",
    "image": "major-16.jpg",
    "arcana": "major",
    "suit": null,
    "number": 16,
    "element": "ไฟ",
    "astrology": "ดาวอังคาร",
    "keywords": {
      "upright": [
        "เปลี่ยนกะทันหัน",
        "ความจริงปรากฏ",
        "รื้อของเก่า",
        "ตื่นรู้",
        "ปลดล็อก"
      ],
      "reversed": [
        "ยื้อไว้",
        "เลี่ยงความจริง",
        "สั่นคลอนภายใน",
        "ค่อย ๆ พัง"
      ]
    }
  },
  {
    "id": "major-17",
    "name": "ดวงดาว",
    "nameTh": "ดวงดาว",
    "nameEn": "The Star",
    "image": "major-17.jpg",
    "arcana": "major",
    "suit": null,
    "number": 17,
    "element": "ลม",
    "astrology": "ราศีกุมภ์",
    "keywords": {
      "upright": [
        "ความหวัง",
        "ฟื้นตัว",
        "แรงบันดาลใจ",
        "ศรัทธา",
        "ใจสงบ"
      ],
      "reversed": [
        "หมดหวัง",
        "ท้อ",
        "ขาดศรัทธา",
        "มองไม่เห็นทาง"
      ]
    }
  },
  {
    "id": "major-18",
    "name": "ดวงจันทร์",
    "nameTh": "ดวงจันทร์",
    "nameEn": "The Moon",
    "image": "major-18.jpg",
    "arcana": "major",
    "suit": null,
    "number": 18,
    "element": "น้ำ",
    "astrology": "ราศีมีน",
    "keywords": {
      "upright": [
        "ความไม่ชัดเจน",
        "ความกลัว",
        "สัญชาตญาณ",
        "ภาพลวง",
        "ความฝัน"
      ],
      "reversed": [
        "เริ่มเห็นชัด",
        "คลายกังวล",
        "ความจริงเผยตัว",
        "ปล่อยความคิดฟุ้ง"
      ]
    }
  },
  {
    "id": "major-19",
    "name": "ดวงอาทิตย์",
    "nameTh": "ดวงอาทิตย์",
    "nameEn": "The Sun",
    "image": "major-19.jpg",
    "arcana": "major",
    "suit": null,
    "number": 19,
    "element": "ไฟ",
    "astrology": "ดวงอาทิตย์",
    "keywords": {
      "upright": [
        "ความสำเร็จ",
        "ความสุข",
        "ความชัดเจน",
        "พลังบวก",
        "เป็นตัวของตัวเอง"
      ],
      "reversed": [
        "ความสุขไม่เต็ม",
        "เหนื่อยล้า",
        "มองไม่เห็นข้อดีตัวเอง",
        "ล่าช้า"
      ]
    }
  },
  {
    "id": "major-20",
    "name": "การตื่นขึ้น",
    "nameTh": "การตื่นขึ้น",
    "nameEn": "Judgement",
    "image": "major-20.jpg",
    "arcana": "major",
    "suit": null,
    "number": 20,
    "element": "ไฟ",
    "astrology": "ดาวพลูโต",
    "keywords": {
      "upright": [
        "ตื่นรู้",
        "เรียกร้องภายใน",
        "ให้อภัย",
        "ทบทวนอดีต",
        "โอกาสครั้งที่สอง"
      ],
      "reversed": [
        "ตัดสินตัวเองแรง",
        "ไม่ยอมให้อภัย",
        "เมินเสียงเรียก",
        "ค้างคาใจ"
      ]
    }
  },
  {
    "id": "major-21",
    "name": "โลก",
    "nameTh": "โลก",
    "nameEn": "The World",
    "image": "major-21.jpg",
    "arcana": "major",
    "suit": null,
    "number": 21,
    "element": "ดิน",
    "astrology": "ดาวเสาร์",
    "keywords": {
      "upright": [
        "ครบรอบ",
        "สำเร็จ",
        "เต็มเต็ม",
        "ปิดจบสวยงาม",
        "ก้าวสู่ระดับใหม่"
      ],
      "reversed": [
        "ใกล้เสร็จแต่ยังไม่จบ",
        "ค้างท้าย",
        "รู้สึกไม่เต็ม",
        "ยื้อไม่ยอมปิด"
      ]
    }
  },
  {
    "id": "wands-01",
    "name": "เอซไม้เท้า",
    "nameTh": "เอซไม้เท้า",
    "nameEn": "Ace of Wands",
    "image": "wands-01.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 1,
    "element": "ไฟ",
    "astrology": "ธาตุไฟบริสุทธิ์ ครอบคลุมราศีเมษ สิงห์ และธนู",
    "keywords": {
      "upright": [
        "ประกายไฟแรก",
        "แรงบันดาลใจ",
        "โอกาสใหม่",
        "ไฟลุกในใจ",
        "อยากลงมือ"
      ],
      "reversed": [
        "ไฟมอด",
        "จุดไม่ติด",
        "ผัดวันประกันพรุ่ง",
        "หมดแรงฮึด"
      ]
    }
  },
  {
    "id": "wands-02",
    "name": "ไม้เท้า 2",
    "nameTh": "ไม้เท้า 2",
    "nameEn": "Two of Wands",
    "image": "wands-02.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 2,
    "element": "ไฟ",
    "astrology": "ดาวอังคารในราศีเมษ",
    "keywords": {
      "upright": [
        "วางแผน",
        "มองไกล",
        "ตัดสินใจ",
        "โลกกว้าง",
        "เตรียมออกเดินทาง"
      ],
      "reversed": [
        "ลังเล",
        "กลัวออกจากที่เดิม",
        "แผนค้าง",
        "คิดเล็กเกินไป"
      ]
    }
  },
  {
    "id": "wands-03",
    "name": "ไม้เท้า 3",
    "nameTh": "ไม้เท้า 3",
    "nameEn": "Three of Wands",
    "image": "wands-03.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 3,
    "element": "ไฟ",
    "astrology": "ดวงอาทิตย์ในราศีเมษ",
    "keywords": {
      "upright": [
        "ผลเริ่มเดิน",
        "ขยายวง",
        "รอผลตอบรับ",
        "มองการณ์ไกล",
        "ร่วมมือ"
      ],
      "reversed": [
        "รอเก้อ",
        "ล่าช้า",
        "ขยายเร็วเกินไป",
        "มองแคบ"
      ]
    }
  },
  {
    "id": "wands-04",
    "name": "ไม้เท้า 4",
    "nameTh": "ไม้เท้า 4",
    "nameEn": "Four of Wands",
    "image": "wands-04.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 4,
    "element": "ไฟ",
    "astrology": "ดาวศุกร์ในราศีเมษ",
    "keywords": {
      "upright": [
        "เฉลิมฉลอง",
        "บ้าน",
        "ความมั่นคง",
        "หมุดหมาย",
        "ครอบครัว"
      ],
      "reversed": [
        "งานฉลองที่ไม่เต็มใจ",
        "บ้านไม่อบอุ่น",
        "ฐานสั่นคลอน",
        "เลื่อนกำหนด"
      ]
    }
  },
  {
    "id": "wands-05",
    "name": "ไม้เท้า 5",
    "nameTh": "ไม้เท้า 5",
    "nameEn": "Five of Wands",
    "image": "wands-05.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 5,
    "element": "ไฟ",
    "astrology": "ดาวเสาร์ในราศีสิงห์",
    "keywords": {
      "upright": [
        "แข่งขัน",
        "ปะทะความเห็น",
        "วุ่นวาย",
        "ซ้อมมือ",
        "ต่างคนต่างพูด"
      ],
      "reversed": [
        "เลี่ยงการเผชิญหน้า",
        "ศึกในใจ",
        "ยอมแพ้ก่อน",
        "ความขัดแย้งซ่อนรูป"
      ]
    }
  },
  {
    "id": "wands-06",
    "name": "ไม้เท้า 6",
    "nameTh": "ไม้เท้า 6",
    "nameEn": "Six of Wands",
    "image": "wands-06.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 6,
    "element": "ไฟ",
    "astrology": "ดาวพฤหัสบดีในราศีสิงห์",
    "keywords": {
      "upright": [
        "ชัยชนะ",
        "ได้รับการยอมรับ",
        "ความภูมิใจ",
        "คนมองเห็น",
        "ข่าวดี"
      ],
      "reversed": [
        "ผลงานถูกมองข้าม",
        "หลงตัวเอง",
        "ชัยชนะที่ว่างเปล่า",
        "กลัวไม่ดีพอ"
      ]
    }
  },
  {
    "id": "wands-07",
    "name": "ไม้เท้า 7",
    "nameTh": "ไม้เท้า 7",
    "nameEn": "Seven of Wands",
    "image": "wands-07.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 7,
    "element": "ไฟ",
    "astrology": "ดาวอังคารในราศีสิงห์",
    "keywords": {
      "upright": [
        "ยืนหยัด",
        "ปกป้องจุดยืน",
        "กล้าค้าน",
        "รักษาที่ยืน",
        "ไม่ยอมถอย"
      ],
      "reversed": [
        "หมดแรงสู้",
        "ยอมทุกอย่าง",
        "ระแวงเกินเหตุ",
        "สู้ผิดเรื่อง"
      ]
    }
  },
  {
    "id": "wands-08",
    "name": "ไม้เท้า 8",
    "nameTh": "ไม้เท้า 8",
    "nameEn": "Eight of Wands",
    "image": "wands-08.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 8,
    "element": "ไฟ",
    "astrology": "ดาวพุธในราศีธนู",
    "keywords": {
      "upright": [
        "เร็ว",
        "ข่าวสาร",
        "ทุกอย่างขยับพร้อมกัน",
        "ไร้อุปสรรค",
        "ตรงเป้า"
      ],
      "reversed": [
        "ล่าช้า",
        "สื่อสารพลาด",
        "รีบจนพลาด",
        "ข่าวไม่มา"
      ]
    }
  },
  {
    "id": "wands-09",
    "name": "ไม้เท้า 9",
    "nameTh": "ไม้เท้า 9",
    "nameEn": "Nine of Wands",
    "image": "wands-09.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 9,
    "element": "ไฟ",
    "astrology": "ดวงจันทร์ในราศีธนู",
    "keywords": {
      "upright": [
        "ทนมาไกล",
        "เหลืออีกนิด",
        "ตั้งการ์ด",
        "ความอึด",
        "บาดเจ็บแต่ยังยืน"
      ],
      "reversed": [
        "หมดพลัง",
        "ระแวงจนปิดตัว",
        "อยากถอย",
        "แบกความเจ็บเก่า"
      ]
    }
  },
  {
    "id": "wands-10",
    "name": "ไม้เท้า 10",
    "nameTh": "ไม้เท้า 10",
    "nameEn": "Ten of Wands",
    "image": "wands-10.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 10,
    "element": "ไฟ",
    "astrology": "ดาวเสาร์ในราศีธนู",
    "keywords": {
      "upright": [
        "แบกหนัก",
        "รับผิดชอบเกินตัว",
        "ใกล้ถึงแต่ล้า",
        "ไม่ยอมวาง",
        "ภาระซ้อนภาระ"
      ],
      "reversed": [
        "ปล่อยวางได้",
        "ยอมขอความช่วยเหลือ",
        "โยนภาระให้คนอื่น",
        "แบกจนพัง"
      ]
    }
  },
  {
    "id": "wands-11",
    "name": "เพจไม้เท้า",
    "nameTh": "เพจไม้เท้า",
    "nameEn": "Page of Wands",
    "image": "wands-11.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 11,
    "element": "ไฟ",
    "astrology": "ธาตุดินในธาตุไฟ เชื่อมกับราศีธาตุไฟทั้งสาม คือ เมษ สิงห์ ธนู",
    "keywords": {
      "upright": [
        "อยากลองของใหม่",
        "ข่าวดี",
        "ความสดใส",
        "กล้าถาม",
        "ใจกล้าแบบเด็ก"
      ],
      "reversed": [
        "เบื่อง่าย",
        "ทำครึ่ง ๆ กลาง ๆ",
        "ขาดวินัย",
        "ข่าวที่ยังไม่มา"
      ]
    }
  },
  {
    "id": "wands-12",
    "name": "อัศวินไม้เท้า",
    "nameTh": "อัศวินไม้เท้า",
    "nameEn": "Knight of Wands",
    "image": "wands-12.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 12,
    "element": "ไฟ",
    "astrology": "ราศีธนู ธาตุไฟ ภายใต้อิทธิพลของดาวอังคาร",
    "keywords": {
      "upright": [
        "พุ่งไปข้างหน้า",
        "กล้าเสี่ยง",
        "เสน่ห์แรง",
        "ผจญภัย",
        "ลงมือทันที"
      ],
      "reversed": [
        "ใจร้อน",
        "หุนหัน",
        "เริ่มแล้วทิ้ง",
        "ดีแต่พูด"
      ]
    }
  },
  {
    "id": "wands-13",
    "name": "ราชินีไม้เท้า",
    "nameTh": "ราชินีไม้เท้า",
    "nameEn": "Queen of Wands",
    "image": "wands-13.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 13,
    "element": "ไฟ",
    "astrology": "ราศีเมษ ธาตุไฟ ภายใต้อิทธิพลของดวงอาทิตย์",
    "keywords": {
      "upright": [
        "มั่นใจ",
        "อบอุ่นและมีเสน่ห์",
        "ดึงดูดคน",
        "รู้คุณค่าตัวเอง",
        "กล้าเป็นตัวเอง"
      ],
      "reversed": [
        "ขี้หึง",
        "หมดความมั่นใจ",
        "แข่งกับคนอื่นในใจ",
        "ให้จนหมดตัว"
      ]
    }
  },
  {
    "id": "wands-14",
    "name": "ราชาไม้เท้า",
    "nameTh": "ราชาไม้เท้า",
    "nameEn": "King of Wands",
    "image": "wands-14.jpg",
    "arcana": "minor",
    "suit": "wands",
    "number": 14,
    "element": "ไฟ",
    "astrology": "ราศีสิงห์ ธาตุไฟ ภายใต้อิทธิพลของดาวพฤหัสบดี",
    "keywords": {
      "upright": [
        "ผู้นำ",
        "วิสัยทัศน์",
        "กล้าตัดสินใจ",
        "บารมี",
        "มองภาพใหญ่"
      ],
      "reversed": [
        "เผด็จการ",
        "หัวร้อน",
        "ใช้อำนาจเกิน",
        "พูดใหญ่ทำไม่ได้"
      ]
    }
  },
  {
    "id": "cups-01",
    "name": "เอซแห่งถ้วย",
    "nameTh": "เอซแห่งถ้วย",
    "nameEn": "Ace of Cups",
    "image": "cups-01.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 1,
    "element": "น้ำ",
    "astrology": "รากธาตุน้ำ — พลังของดวงจันทร์ที่หล่อเลี้ยงราศีกรกฎ พิจิก และมีน",
    "keywords": {
      "upright": [
        "ใจที่เปิด",
        "ความรู้สึกใหม่",
        "ความรักบริสุทธิ์",
        "แรงบันดาลใจ",
        "การให้อภัย"
      ],
      "reversed": [
        "ปิดใจ",
        "อารมณ์ตัน",
        "รักตัวเองไม่พอ"
      ]
    }
  },
  {
    "id": "cups-02",
    "name": "สองถ้วย",
    "nameTh": "สองถ้วย",
    "nameEn": "Two of Cups",
    "image": "cups-02.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 2,
    "element": "น้ำ",
    "astrology": "ดาวศุกร์ในราศีกรกฎ",
    "keywords": {
      "upright": [
        "ใจตรงกัน",
        "คู่แท้",
        "ความผูกพัน",
        "การให้เกียรติ",
        "ข้อตกลงที่ดี"
      ],
      "reversed": [
        "ไม่สมดุล",
        "เข้าใจผิด",
        "ฝ่ายเดียว",
        "ระยะห่าง"
      ]
    }
  },
  {
    "id": "cups-03",
    "name": "สามถ้วย",
    "nameTh": "สามถ้วย",
    "nameEn": "Three of Cups",
    "image": "cups-03.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 3,
    "element": "น้ำ",
    "astrology": "ดาวพุธในราศีกรกฎ",
    "keywords": {
      "upright": [
        "มิตรภาพ",
        "การเฉลิมฉลอง",
        "กลุ่มคนที่ใช่",
        "ข่าวดี",
        "การแบ่งปัน"
      ],
      "reversed": [
        "วงแตก",
        "นินทา",
        "สังคมที่เหนื่อย",
        "รู้สึกโดดเดี่ยวในฝูงชน"
      ]
    }
  },
  {
    "id": "cups-04",
    "name": "สี่ถ้วย",
    "nameTh": "สี่ถ้วย",
    "nameEn": "Four of Cups",
    "image": "cups-04.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 4,
    "element": "น้ำ",
    "astrology": "ดวงจันทร์ในราศีกรกฎ",
    "keywords": {
      "upright": [
        "เบื่อหน่าย",
        "มองข้ามโอกาส",
        "ทบทวนตัวเอง",
        "อิ่มตัว",
        "ถอยมามอง"
      ],
      "reversed": [
        "ตื่นจากความเฉื่อย",
        "เห็นค่าใหม่",
        "พร้อมรับ",
        "ออกจากถ้ำ"
      ]
    }
  },
  {
    "id": "cups-05",
    "name": "ห้าถ้วย",
    "nameTh": "ห้าถ้วย",
    "nameEn": "Five of Cups",
    "image": "cups-05.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 5,
    "element": "น้ำ",
    "astrology": "ดาวอังคารในราศีพิจิก",
    "keywords": {
      "upright": [
        "ความเสียใจ",
        "การสูญเสีย",
        "เสียดายอดีต",
        "บทเรียน",
        "ยังมีสิ่งที่เหลือ"
      ],
      "reversed": [
        "เริ่มก้าวข้าม",
        "ให้อภัย",
        "หันกลับมามอง",
        "เยียวยา"
      ]
    }
  },
  {
    "id": "cups-06",
    "name": "หกถ้วย",
    "nameTh": "หกถ้วย",
    "nameEn": "Six of Cups",
    "image": "cups-06.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 6,
    "element": "น้ำ",
    "astrology": "ดวงอาทิตย์ในราศีพิจิก",
    "keywords": {
      "upright": [
        "ความทรงจำ",
        "คนเก่ากลับมา",
        "ความบริสุทธิ์ใจ",
        "บ้าน",
        "ความอบอุ่น"
      ],
      "reversed": [
        "ติดอยู่ในอดีต",
        "โหยหาสิ่งที่ผ่านไป",
        "ไม่ยอมโต"
      ]
    }
  },
  {
    "id": "cups-07",
    "name": "เจ็ดถ้วย",
    "nameTh": "เจ็ดถ้วย",
    "nameEn": "Seven of Cups",
    "image": "cups-07.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 7,
    "element": "น้ำ",
    "astrology": "ดาวศุกร์ในราศีพิจิก",
    "keywords": {
      "upright": [
        "ทางเลือกมาก",
        "ภาพลวง",
        "เพ้อฝัน",
        "ลังเล",
        "ต้องคัดกรอง"
      ],
      "reversed": [
        "เห็นชัดขึ้น",
        "ตัดสินใจได้",
        "เลิกหลอกตัวเอง",
        "โฟกัส"
      ]
    }
  },
  {
    "id": "cups-08",
    "name": "แปดถ้วย",
    "nameTh": "แปดถ้วย",
    "nameEn": "Eight of Cups",
    "image": "cups-08.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 8,
    "element": "น้ำ",
    "astrology": "ดาวเสาร์ในราศีมีน",
    "keywords": {
      "upright": [
        "จากลา",
        "ออกเดินทาง",
        "หาความหมาย",
        "วางสิ่งที่ไม่ใช่",
        "กล้าเดินต่อ"
      ],
      "reversed": [
        "ลังเลจะไป",
        "กลับไปที่เดิม",
        "กลัวการเปลี่ยน",
        "ยื้อไว้"
      ]
    }
  },
  {
    "id": "cups-09",
    "name": "เก้าถ้วย",
    "nameTh": "เก้าถ้วย",
    "nameEn": "Nine of Cups",
    "image": "cups-09.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 9,
    "element": "น้ำ",
    "astrology": "ดาวพฤหัสบดีในราศีมีน",
    "keywords": {
      "upright": [
        "สมหวัง",
        "ความพอใจ",
        "ความสุขส่วนตัว",
        "รางวัลของตัวเอง",
        "อิ่มใจ"
      ],
      "reversed": [
        "ได้แล้วยังไม่พอ",
        "สุขผิวเผิน",
        "ตามใจตัวเองเกิน",
        "ความหวังคลาด"
      ]
    }
  },
  {
    "id": "cups-10",
    "name": "สิบถ้วย",
    "nameTh": "สิบถ้วย",
    "nameEn": "Ten of Cups",
    "image": "cups-10.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 10,
    "element": "น้ำ",
    "astrology": "ดาวอังคารในราศีมีน",
    "keywords": {
      "upright": [
        "ครอบครัว",
        "ความสุขที่ยั่งยืน",
        "ความกลมเกลียว",
        "บ้านที่อบอุ่น",
        "ลงตัว"
      ],
      "reversed": [
        "ภาพสวยที่ไม่ตรงข้างใน",
        "ร้าวในบ้าน",
        "คาดหวังเกินจริง"
      ]
    }
  },
  {
    "id": "cups-11",
    "name": "เพจแห่งถ้วย",
    "nameTh": "เพจแห่งถ้วย",
    "nameEn": "Page of Cups",
    "image": "cups-11.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 11,
    "element": "น้ำ",
    "astrology": "ธาตุดินในธาตุน้ำ — พลังตั้งต้นของราศีธาตุน้ำ กรกฎ พิจิก และมีน",
    "keywords": {
      "upright": [
        "ข่าวดีเรื่องใจ",
        "ความอ่อนโยน",
        "ความคิดสร้างสรรค์",
        "เปิดรับ",
        "ใจซื่อ"
      ],
      "reversed": [
        "งอน",
        "อ่อนไหวเกินไป",
        "หนีความจริง",
        "ยังไม่โต"
      ]
    }
  },
  {
    "id": "cups-12",
    "name": "อัศวินแห่งถ้วย",
    "nameTh": "อัศวินแห่งถ้วย",
    "nameEn": "Knight of Cups",
    "image": "cups-12.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 12,
    "element": "น้ำ",
    "astrology": "ธาตุลมในธาตุน้ำ — ช่วงรอยต่อที่พลังน้ำเคลื่อนเข้าสู่ราศีมีน",
    "keywords": {
      "upright": [
        "คำเชิญชวน",
        "โรแมนติก",
        "ตามเสียงหัวใจ",
        "อุดมคติ",
        "ข้อเสนอที่น่าสนใจ"
      ],
      "reversed": [
        "สัญญาลม ๆ",
        "อารมณ์นำเหตุผล",
        "ไม่รักษาคำ",
        "เพ้อ"
      ]
    }
  },
  {
    "id": "cups-13",
    "name": "ราชินีแห่งถ้วย",
    "nameTh": "ราชินีแห่งถ้วย",
    "nameEn": "Queen of Cups",
    "image": "cups-13.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 13,
    "element": "น้ำ",
    "astrology": "ธาตุน้ำในธาตุน้ำ — ราศีกรกฎ ที่ปกครองโดยดวงจันทร์",
    "keywords": {
      "upright": [
        "เข้าอกเข้าใจ",
        "สัญชาตญาณแม่นยำ",
        "ใจเย็น",
        "ผู้ให้",
        "ความอ่อนโยนที่มั่นคง"
      ],
      "reversed": [
        "แบกอารมณ์คนอื่น",
        "เผลอควบคุมด้วยความหวังดี",
        "ไร้ขอบเขต",
        "เหนื่อยใจ"
      ]
    }
  },
  {
    "id": "cups-14",
    "name": "ราชาแห่งถ้วย",
    "nameTh": "ราชาแห่งถ้วย",
    "nameEn": "King of Cups",
    "image": "cups-14.jpg",
    "arcana": "minor",
    "suit": "cups",
    "number": 14,
    "element": "น้ำ",
    "astrology": "ธาตุไฟในธาตุน้ำ — ราศีพิจิก ที่มีความลึกและพลังควบคุมตัวเอง",
    "keywords": {
      "upright": [
        "ใจนิ่ง",
        "ที่ปรึกษาที่ดี",
        "ควบคุมอารมณ์ได้",
        "ใจกว้าง",
        "ผู้ใหญ่ที่พึ่งได้"
      ],
      "reversed": [
        "เก็บกดอารมณ์",
        "เย็นชา",
        "อารมณ์ระเบิด",
        "ปากไม่ตรงใจ"
      ]
    }
  },
  {
    "id": "swords-01",
    "name": "เอซแห่งดาบ",
    "nameTh": "เอซแห่งดาบ",
    "nameEn": "Ace of Swords",
    "image": "swords-01.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 1,
    "element": "ลม",
    "astrology": "ธาตุลมในภาพรวม ครอบคลุมราศีเมถุน ตุลย์ และกุมภ์",
    "keywords": {
      "upright": [
        "ความชัดเจน",
        "ความจริง",
        "ไอเดียใหม่",
        "ตัดสินใจเด็ดขาด",
        "พลังของคำพูด"
      ],
      "reversed": [
        "สับสน",
        "ข้อมูลไม่ครบ",
        "พูดแรงเกินไป",
        "คิดวนไม่จบ"
      ]
    }
  },
  {
    "id": "swords-02",
    "name": "สองแห่งดาบ",
    "nameTh": "สองแห่งดาบ",
    "nameEn": "Two of Swords",
    "image": "swords-02.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 2,
    "element": "ลม",
    "astrology": "ดวงจันทร์ในราศีตุลย์",
    "keywords": {
      "upright": [
        "ลังเล",
        "ทางสองแพร่ง",
        "ปิดตาไม่มอง",
        "ถ่วงดุล",
        "ยังไม่เลือก"
      ],
      "reversed": [
        "เห็นความจริง",
        "ตัดสินใจได้",
        "หมดเวลาเลี่ยง"
      ]
    }
  },
  {
    "id": "swords-03",
    "name": "สามแห่งดาบ",
    "nameTh": "สามแห่งดาบ",
    "nameEn": "Three of Swords",
    "image": "swords-03.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 3,
    "element": "ลม",
    "astrology": "ดาวเสาร์ในราศีตุลย์",
    "keywords": {
      "upright": [
        "ความเจ็บจากความจริง",
        "ผิดหวัง",
        "คำพูดที่กระทบใจ",
        "ช่วงเสียใจ"
      ],
      "reversed": [
        "เริ่มฟื้น",
        "ให้อภัย",
        "แผลค่อยปิด"
      ]
    }
  },
  {
    "id": "swords-04",
    "name": "สี่แห่งดาบ",
    "nameTh": "สี่แห่งดาบ",
    "nameEn": "Four of Swords",
    "image": "swords-04.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 4,
    "element": "ลม",
    "astrology": "ดาวพฤหัสบดีในราศีตุลย์",
    "keywords": {
      "upright": [
        "พักผ่อน",
        "ถอยตั้งหลัก",
        "ความเงียบ",
        "ฟื้นกำลัง",
        "หยุดคิดชั่วคราว"
      ],
      "reversed": [
        "กลับมาเดินต่อ",
        "ฝืนจนล้า",
        "พักไม่ลง"
      ]
    }
  },
  {
    "id": "swords-05",
    "name": "ห้าแห่งดาบ",
    "nameTh": "ห้าแห่งดาบ",
    "nameEn": "Five of Swords",
    "image": "swords-05.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 5,
    "element": "ลม",
    "astrology": "ดาวศุกร์ในราศีกุมภ์",
    "keywords": {
      "upright": [
        "ความขัดแย้ง",
        "ชนะแต่ไม่คุ้ม",
        "ทิฐิ",
        "คำพูดกระทบกระทั่ง"
      ],
      "reversed": [
        "คลี่คลาย",
        "ยอมถอย",
        "คืนดี",
        "วางเรื่องลง"
      ]
    }
  },
  {
    "id": "swords-06",
    "name": "หกแห่งดาบ",
    "nameTh": "หกแห่งดาบ",
    "nameEn": "Six of Swords",
    "image": "swords-06.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 6,
    "element": "ลม",
    "astrology": "ดาวพุธในราศีกุมภ์",
    "keywords": {
      "upright": [
        "เปลี่ยนผ่าน",
        "ย้ายออกจากที่เดิม",
        "น้ำนิ่งขึ้น",
        "เดินทาง",
        "ค่อย ๆ ดีขึ้น"
      ],
      "reversed": [
        "ใจยังติดที่เดิม",
        "ไปไม่ได้สักที",
        "ลากยาว"
      ]
    }
  },
  {
    "id": "swords-07",
    "name": "เจ็ดแห่งดาบ",
    "nameTh": "เจ็ดแห่งดาบ",
    "nameEn": "Seven of Swords",
    "image": "swords-07.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 7,
    "element": "ลม",
    "astrology": "ดวงจันทร์ในราศีกุมภ์",
    "keywords": {
      "upright": [
        "ชั้นเชิง",
        "เรื่องที่ยังไม่ถูกพูด",
        "ปิดบัง",
        "เลี่ยงการเผชิญหน้า"
      ],
      "reversed": [
        "ความจริงเปิดเผย",
        "ยอมรับ",
        "เคลียร์ให้ชัด"
      ]
    }
  },
  {
    "id": "swords-08",
    "name": "แปดแห่งดาบ",
    "nameTh": "แปดแห่งดาบ",
    "nameEn": "Eight of Swords",
    "image": "swords-08.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 8,
    "element": "ลม",
    "astrology": "ดาวพฤหัสบดีในราศีเมถุน",
    "keywords": {
      "upright": [
        "รู้สึกติดกับ",
        "กรอบในหัว",
        "ไม่กล้าขยับ",
        "มองไม่เห็นทางเลือก"
      ],
      "reversed": [
        "เริ่มคลาย",
        "เห็นทางออก",
        "กล้าขยับ"
      ]
    }
  },
  {
    "id": "swords-09",
    "name": "เก้าแห่งดาบ",
    "nameTh": "เก้าแห่งดาบ",
    "nameEn": "Nine of Swords",
    "image": "swords-09.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 9,
    "element": "ลม",
    "astrology": "ดาวอังคารในราศีเมถุน",
    "keywords": {
      "upright": [
        "ความกังวล",
        "คิดมากตอนกลางคืน",
        "ความกลัวในหัว",
        "นอนไม่หลับ"
      ],
      "reversed": [
        "ความกังวลคลาย",
        "มองตามจริง",
        "เริ่มปล่อยวาง"
      ]
    }
  },
  {
    "id": "swords-10",
    "name": "สิบแห่งดาบ",
    "nameTh": "สิบแห่งดาบ",
    "nameEn": "Ten of Swords",
    "image": "swords-10.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 10,
    "element": "ลม",
    "astrology": "ดวงอาทิตย์ในราศีเมถุน",
    "keywords": {
      "upright": [
        "จุดต่ำสุดผ่านไปแล้ว",
        "บทหนึ่งปิดลง",
        "หมดแรง",
        "เริ่มนับหนึ่งใหม่"
      ],
      "reversed": [
        "ลุกขึ้นได้",
        "ฟื้นตัว",
        "แรงกลับมา"
      ]
    }
  },
  {
    "id": "swords-11",
    "name": "บริวารแห่งดาบ",
    "nameTh": "บริวารแห่งดาบ",
    "nameEn": "Page of Swords",
    "image": "swords-11.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 11,
    "element": "ลม",
    "astrology": "ธาตุลมในวัยเริ่มต้น เชื่อมโยงกับราศีเมถุนเป็นหลัก",
    "keywords": {
      "upright": [
        "อยากรู้อยากเห็น",
        "ข่าวสาร",
        "เริ่มเรียนรู้",
        "ช่างสังเกต",
        "พูดตรง"
      ],
      "reversed": [
        "พูดก่อนคิด",
        "ข่าวลือ",
        "ดีแต่พูด",
        "ฟุ้งซ่าน"
      ]
    }
  },
  {
    "id": "swords-12",
    "name": "อัศวินแห่งดาบ",
    "nameTh": "อัศวินแห่งดาบ",
    "nameEn": "Knight of Swords",
    "image": "swords-12.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 12,
    "element": "ลม",
    "astrology": "ราศีเมถุน ผสมแรงผลักดันของดาวอังคาร",
    "keywords": {
      "upright": [
        "พุ่งไปข้างหน้า",
        "ตัดสินใจเร็ว",
        "กล้าพูด",
        "จังหวะเร่ง",
        "มุ่งมั่น"
      ],
      "reversed": [
        "ใจร้อน",
        "คำพูดแรง",
        "รีบจนพลาด",
        "หุนหัน"
      ]
    }
  },
  {
    "id": "swords-13",
    "name": "ราชินีแห่งดาบ",
    "nameTh": "ราชินีแห่งดาบ",
    "nameEn": "Queen of Swords",
    "image": "swords-13.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 13,
    "element": "ลม",
    "astrology": "ราศีตุลย์",
    "keywords": {
      "upright": [
        "สายตาคม",
        "พูดตรงแต่หวังดี",
        "มีขอบเขต",
        "อิสระทางความคิด",
        "ผ่านเรื่องมาเยอะ"
      ],
      "reversed": [
        "เย็นชา",
        "ตัดสินเร็วเกิน",
        "ตั้งการ์ดสูง"
      ]
    }
  },
  {
    "id": "swords-14",
    "name": "ราชาแห่งดาบ",
    "nameTh": "ราชาแห่งดาบ",
    "nameEn": "King of Swords",
    "image": "swords-14.jpg",
    "arcana": "minor",
    "suit": "swords",
    "number": 14,
    "element": "ลม",
    "astrology": "ราศีกุมภ์",
    "keywords": {
      "upright": [
        "เหตุผล",
        "หลักการ",
        "ผู้ใหญ่ที่พึ่งได้",
        "ตัดสินใจอย่างมั่นคง",
        "มองภาพใหญ่"
      ],
      "reversed": [
        "ยึดความคิดตัวเอง",
        "เย็นจนห่าง",
        "ควบคุมมากไป"
      ]
    }
  },
  {
    "id": "pentacles-01",
    "name": "เอซแห่งเหรียญ",
    "nameTh": "เอซแห่งเหรียญ",
    "nameEn": "Ace of Pentacles",
    "image": "pentacles-01.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 1,
    "element": "ดิน",
    "astrology": "ธาตุดินในรูปบริสุทธิ์ ครอบคลุมราศีพฤษภ กันย์ และมังกร",
    "keywords": {
      "upright": [
        "โอกาสใหม่",
        "เมล็ดพันธุ์",
        "รากฐาน",
        "ความมั่นคง",
        "ลงมือจริง"
      ],
      "reversed": [
        "โอกาสหลุดมือ",
        "เริ่มไม่ลง",
        "ยึดติดวัตถุ",
        "วางแผนหลวม"
      ]
    }
  },
  {
    "id": "pentacles-02",
    "name": "สองแห่งเหรียญ",
    "nameTh": "สองแห่งเหรียญ",
    "nameEn": "Two of Pentacles",
    "image": "pentacles-02.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 2,
    "element": "ดิน",
    "astrology": "ดาวพฤหัสในราศีมังกร",
    "keywords": {
      "upright": [
        "สมดุล",
        "ยืดหยุ่น",
        "จัดลำดับ",
        "หลายบทบาท",
        "ปรับตัว"
      ],
      "reversed": [
        "จัดการไม่ทัน",
        "เสียสมดุล",
        "ผัดวันประกันพรุ่ง",
        "รับมากเกินไป"
      ]
    }
  },
  {
    "id": "pentacles-03",
    "name": "สามแห่งเหรียญ",
    "nameTh": "สามแห่งเหรียญ",
    "nameEn": "Three of Pentacles",
    "image": "pentacles-03.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 3,
    "element": "ดิน",
    "astrology": "ดาวอังคารในราศีมังกร",
    "keywords": {
      "upright": [
        "ทีมเวิร์ก",
        "ฝีมือ",
        "การยอมรับ",
        "ร่วมมือ",
        "เรียนรู้งาน"
      ],
      "reversed": [
        "แบกคนเดียว",
        "ไม่ถูกเห็นค่า",
        "สื่อสารพลาด",
        "งานไม่ประณีต"
      ]
    }
  },
  {
    "id": "pentacles-04",
    "name": "สี่แห่งเหรียญ",
    "nameTh": "สี่แห่งเหรียญ",
    "nameEn": "Four of Pentacles",
    "image": "pentacles-04.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 4,
    "element": "ดิน",
    "astrology": "ดวงอาทิตย์ในราศีมังกร",
    "keywords": {
      "upright": [
        "ความมั่นคง",
        "เก็บออม",
        "ระมัดระวัง",
        "ยึดไว้แน่น",
        "ตั้งขอบเขต"
      ],
      "reversed": [
        "หวงเกินไป",
        "กลัวขาด",
        "ปล่อยวางไม่ได้",
        "ใช้จ่ายสวนทาง"
      ]
    }
  },
  {
    "id": "pentacles-05",
    "name": "ห้าแห่งเหรียญ",
    "nameTh": "ห้าแห่งเหรียญ",
    "nameEn": "Five of Pentacles",
    "image": "pentacles-05.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 5,
    "element": "ดิน",
    "astrology": "ดาวพุธในราศีพฤษภ",
    "keywords": {
      "upright": [
        "ช่วงขัดสน",
        "ความเหงา",
        "มองข้ามความช่วยเหลือ",
        "บททดสอบ",
        "ศรัทธา"
      ],
      "reversed": [
        "ฟื้นตัว",
        "ได้รับความช่วยเหลือ",
        "กลับเข้าที่",
        "ยอมเปิดใจ"
      ]
    }
  },
  {
    "id": "pentacles-06",
    "name": "หกแห่งเหรียญ",
    "nameTh": "หกแห่งเหรียญ",
    "nameEn": "Six of Pentacles",
    "image": "pentacles-06.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 6,
    "element": "ดิน",
    "astrology": "ดวงจันทร์ในราศีพฤษภ",
    "keywords": {
      "upright": [
        "การให้และรับ",
        "ความเอื้อเฟื้อ",
        "ความช่วยเหลือ",
        "ความยุติธรรม",
        "แบ่งปัน"
      ],
      "reversed": [
        "ให้ฝ่ายเดียว",
        "มีเงื่อนไขแฝง",
        "อำนาจไม่เท่ากัน",
        "รับไม่เป็น"
      ]
    }
  },
  {
    "id": "pentacles-07",
    "name": "เจ็ดแห่งเหรียญ",
    "nameTh": "เจ็ดแห่งเหรียญ",
    "nameEn": "Seven of Pentacles",
    "image": "pentacles-07.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 7,
    "element": "ดิน",
    "astrology": "ดาวเสาร์ในราศีพฤษภ",
    "keywords": {
      "upright": [
        "รอผล",
        "ประเมินผล",
        "ความอดทน",
        "ลงแรงระยะยาว",
        "ทบทวน"
      ],
      "reversed": [
        "ใจร้อน",
        "ลงแรงผิดที่",
        "ท้อกลางคัน",
        "ผลไม่คุ้ม"
      ]
    }
  },
  {
    "id": "pentacles-08",
    "name": "แปดแห่งเหรียญ",
    "nameTh": "แปดแห่งเหรียญ",
    "nameEn": "Eight of Pentacles",
    "image": "pentacles-08.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 8,
    "element": "ดิน",
    "astrology": "ดวงอาทิตย์ในราศีกันย์",
    "keywords": {
      "upright": [
        "ฝึกฝน",
        "ตั้งใจทำ",
        "พัฒนาทักษะ",
        "ใส่ใจรายละเอียด",
        "ขยัน"
      ],
      "reversed": [
        "ทำไปวัน ๆ",
        "หมดไฟ",
        "ลวก",
        "ไม่ยอมพัฒนา"
      ]
    }
  },
  {
    "id": "pentacles-09",
    "name": "เก้าแห่งเหรียญ",
    "nameTh": "เก้าแห่งเหรียญ",
    "nameEn": "Nine of Pentacles",
    "image": "pentacles-09.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 9,
    "element": "ดิน",
    "astrology": "ดาวศุกร์ในราศีกันย์",
    "keywords": {
      "upright": [
        "พึ่งพาตัวเองได้",
        "ผลของความอดทน",
        "ความสง่างาม",
        "อิสระทางใจ",
        "ภูมิใจ"
      ],
      "reversed": [
        "ยังไม่มั่นคงจริง",
        "เหงาในความสำเร็จ",
        "ฟุ้งเฟ้อ",
        "พึ่งคนอื่นมากไป"
      ]
    }
  },
  {
    "id": "pentacles-10",
    "name": "สิบแห่งเหรียญ",
    "nameTh": "สิบแห่งเหรียญ",
    "nameEn": "Ten of Pentacles",
    "image": "pentacles-10.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 10,
    "element": "ดิน",
    "astrology": "ดาวพุธในราศีกันย์",
    "keywords": {
      "upright": [
        "ครอบครัว",
        "รากฐานมั่นคง",
        "ความมั่นคงระยะยาว",
        "การส่งต่อ",
        "บ้าน"
      ],
      "reversed": [
        "เรื่องในบ้าน",
        "ภาระที่รับมา",
        "มองแค่ระยะสั้น",
        "รากสั่นคลอน"
      ]
    }
  },
  {
    "id": "pentacles-11",
    "name": "เด็กหนุ่มแห่งเหรียญ",
    "nameTh": "เด็กหนุ่มแห่งเหรียญ",
    "nameEn": "Page of Pentacles",
    "image": "pentacles-11.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 11,
    "element": "ดิน",
    "astrology": "ธาตุดินในระดับผู้เริ่มต้น เชื่อมโยงกับราศีพฤษภ กันย์ และมังกร",
    "keywords": {
      "upright": [
        "เริ่มเรียนรู้",
        "ความอยากรู้",
        "ตั้งใจจริง",
        "ข่าวเรื่องงาน",
        "ลงมือทดลอง"
      ],
      "reversed": [
        "ไม่โฟกัส",
        "เลื่อนไปเรื่อย",
        "ขาดวินัย",
        "เริ่มแล้วไม่จบ"
      ]
    }
  },
  {
    "id": "pentacles-12",
    "name": "อัศวินแห่งเหรียญ",
    "nameTh": "อัศวินแห่งเหรียญ",
    "nameEn": "Knight of Pentacles",
    "image": "pentacles-12.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 12,
    "element": "ดิน",
    "astrology": "ช่วงปลายราศีสิงห์ถึงราศีกันย์ ตัวแทนของธาตุดินที่ลงมือทำ",
    "keywords": {
      "upright": [
        "สม่ำเสมอ",
        "น่าเชื่อถือ",
        "ทำทีละขั้น",
        "อดทน",
        "รับผิดชอบ"
      ],
      "reversed": [
        "ช้าเกินไป",
        "ติดกรอบ",
        "ดื้อเงียบ",
        "ย่ำอยู่กับที่"
      ]
    }
  },
  {
    "id": "pentacles-13",
    "name": "ราชินีแห่งเหรียญ",
    "nameTh": "ราชินีแห่งเหรียญ",
    "nameEn": "Queen of Pentacles",
    "image": "pentacles-13.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 13,
    "element": "ดิน",
    "astrology": "ช่วงปลายราศีธนูถึงราศีมังกร ตัวแทนของธาตุดินที่โอบอุ้ม",
    "keywords": {
      "upright": [
        "ดูแลคน",
        "อบอุ่น",
        "จัดการเก่ง",
        "ติดดิน",
        "พึ่งพาได้"
      ],
      "reversed": [
        "แบกคนอื่นจนหมดแรง",
        "กังวลเรื่องปากท้อง",
        "ละเลยตัวเอง",
        "จู้จี้"
      ]
    }
  },
  {
    "id": "pentacles-14",
    "name": "ราชาแห่งเหรียญ",
    "nameTh": "ราชาแห่งเหรียญ",
    "nameEn": "King of Pentacles",
    "image": "pentacles-14.jpg",
    "arcana": "minor",
    "suit": "pentacles",
    "number": 14,
    "element": "ดิน",
    "astrology": "ช่วงปลายราศีเมษถึงราศีพฤษภ ตัวแทนของธาตุดินที่ตั้งมั่น",
    "keywords": {
      "upright": [
        "มั่นคง",
        "ผู้นำที่ไว้ใจได้",
        "สร้างมาด้วยตัวเอง",
        "ใจกว้าง",
        "มองยาว"
      ],
      "reversed": [
        "ยึดติดวัตถุ",
        "ควบคุมมากไป",
        "หัวแข็ง",
        "วัดคนที่ผลงาน"
      ]
    }
  }
] as const;

const BY_ID = new Map<string, CardSummary>(CARD_SUMMARIES.map((c) => [c.id, c]));

/**
 * ดึงข้อมูลสรุปไพ่ตาม id
 * กฎเหล็กข้อ 14 (Zero Fabricated Cards Policy): คืน undefined เมื่อหาไม่เจอ ห้ามกุไพ่มาแทนเด็ดขาด
 */
export function cardSummaryById(id?: string | null): CardSummary | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

/**
 * ดึงข้อมูลสรุปไพ่ตามลำดับ index (0-77)
 * กฎเหล็กข้อ 14 (Zero Fabricated Cards Policy): คืน undefined เมื่อเกินขอบเขต ห้ามกุไพ่มาแทนเด็ดขาด
 */
export function cardSummaryByIndex(index?: number | null): CardSummary | undefined {
  if (typeof index !== "number" || index < 0 || index >= CARD_SUMMARIES.length) {
    return undefined;
  }
  return CARD_SUMMARIES[index];
}
