// Auto-generated by scripts/i18n-import.ts — DO NOT EDIT MANUALLY
export interface SpreadTopicEnData {
  seoTitleEn?: string;
  metaDescriptionEn?: string;
  titleEn?: string;
  headingEn?: string;
  taglineEn?: string;
  editorialIntroEn?: string[];
  faqsEn?: Array<{ question: string; answer: string }>;
}

export const SPREAD_TOPICS_EN: Record<string, SpreadTopicEnData> = {
  "love": {
    "seoTitleEn": "Love Tarot Spreads: Free In-Depth 1909 Oracle Readings",
    "metaDescriptionEn": "Explore 5 dedicated love tarot spreads. Decode their hidden feelings, ex reconciliation odds, soulmate connections, and 6-card relationship deep dives.",
    "titleEn": "Love Tarot Spreads",
    "headingEn": "Love and Relationship Tarot Spreads",
    "taglineEn": "Untangle matters of the heart, decode true feelings, and illuminate your romantic path.",
    "editorialIntroEn": [
      "Love is the most delicate and profound dimension of human experience. When uncertainty clouds a relationship, silence creates anxiety, or you wonder whether to hold on or let go, the 1909 Rider-Waite tarot acts as an honest mirror reflecting unspoken emotional currents. It offers clarity without dogma.",
      "In this sacred sanctuary, SeerTarot offers five specialized spreads: How They Feel (4 cards), Ex Reconciliation (4 cards), Soulmate Energy (5 cards), Two Hearts Relationship (5 cards), and Complex Relationship Dynamics (6 cards).",
      "Guidance for Love Readings: Inhale deeply, soften anxiety, and focus on the person or situation with an open heart ready for truth. Pure intention invites the most articulate counsel from the cards."
    ],
    "faqsEn": [
      {
        "question": "What questions yield the most illuminating love tarot readings?",
        "answer": "Formulate open-ended questions focused on mutual growth, such as 'What is their true attitude toward our connection?' or 'How can I best navigate this transition?' Avoid binary yes/no questions to unlock richer emotional nuances."
      },
      {
        "question": "Do challenging cards like The Tower or Three of Swords mean a breakup?",
        "answer": "Not always. Challenging cards often signal the dismantling of false assumptions or the opening of vulnerable wounds so genuine healing can take place."
      },
      {
        "question": "How frequently should I consult the cards on the same relationship?",
        "answer": "Allow at least 2 to 4 weeks between identical inquiries, or wait until real-world developments alter the situation. Over-reading creates unnecessary anxiety."
      }
    ]
  },
  "career": {
    "seoTitleEn": "Career Tarot Spreads: Work, Promotion, and Crossroads",
    "metaDescriptionEn": "Discover 3 focused career tarot spreads: work situation, staying vs. leaving, and two-choice crossroads. Provably fair strategic guidance.",
    "titleEn": "Career Tarot Spreads",
    "headingEn": "Career and Vocation Tarot Spreads",
    "taglineEn": "Evaluate your strengths, promotion prospects, and strategic moves in the workplace.",
    "editorialIntroEn": [
      "Your professional life is a vital arena of purpose, creative growth, and material sustenance. When facing workplace stagnation, toxic office politics, or dilemmas about staying or resigning, the 1909 Rider-Waite deck—especially Wands and Pentacles—delivers concrete reflections on your resources, ambitions, and competitive environment.",
      "We provide three robust spreads: Career & Advancement (5 cards) for a comprehensive overview, Staying vs. Leaving (5 cards) for an objective comparison of paths, and the Decision Crossroads Spread (5 cards) to illuminate blind spots before a major pivot.",
      "Career Reading Philosophy: Regard each card as a strategic executive consultant rather than an unalterable verdict. Use its guidance to refine negotiations, upskill deliberately, and advance with quiet confidence."
    ],
    "faqsEn": [
      {
        "question": "Which spread is best if I am debating whether to quit or stay?",
        "answer": "The 'Staying vs. Leaving (5 Cards)' spread is specifically structured to compare both trajectories side by side across growth potential, compensation, and emotional peace of mind."
      },
      {
        "question": "Can tarot indicate when a new job offer will arrive?",
        "answer": "Yes. Elemental speed indicates timing: Wands and Swords signal rapid developments, whereas Pentacles point to thorough, methodical corporate processes."
      }
    ]
  },
  "money": {
    "seoTitleEn": "Wealth & Money Tarot Spreads: Financial Clarity & Luck",
    "metaDescriptionEn": "Free money and finance tarot spreads. Analyze cash flow, investment opportunities, debt elimination strategies, and abundance mindset with 1909 tarot.",
    "titleEn": "Money Tarot Spreads",
    "headingEn": "Wealth and Financial Tarot Spreads",
    "taglineEn": "Identify abundance blocks, assess investment risks, and build long-term financial security.",
    "editorialIntroEn": [
      "Financial security directly impacts your peace of mind and personal sovereignty. Tarot approaches wealth not as superficial greed, but as elemental energy and tangible discipline. The Suit of Pentacles reveals how your subconscious beliefs govern your relationship with earning, spending, and preserving capital.",
      "Consult our specialized 5-Card Financial & Wealth Spread to examine your current cash flow, latent opportunities, hidden expenses, and the ultimate financial harvest of your current trajectory.",
      "Money Reading Philosophy: The cards provide an objective fiscal audit of your energy. Pair tarot insights with rigorous real-world budgeting and prudent risk management."
    ],
    "faqsEn": [
      {
        "question": "Can tarot guarantee lottery numbers or quick windfall profits?",
        "answer": "No. Authentic tarot deals with sustainable value creation, market timing, and personal prudence. It is a strategic tool, not speculative gambling."
      },
      {
        "question": "What does drawing the Five of Pentacles indicate?",
        "answer": "It highlights acute scarcity worries or overlooking accessible resources. It counsels temporary austerity while reaching out for support that is closer than you realize."
      }
    ]
  },
  "health": {
    "seoTitleEn": "Wellness Tarot Spreads: Energy, Stress, and Healing",
    "metaDescriptionEn": "Explore wellness and chakra tarot spreads for stress relief and emotional healing. Discover energetic balance with the 1909 Rider-Waite deck.",
    "titleEn": "Health & Wellness Spreads",
    "headingEn": "Holistic Health and Energetic Wellness",
    "taglineEn": "Diagnose burnout, restore inner equilibrium, and nurture physical and emotional vitality.",
    "editorialIntroEn": [
      "True well-being is the harmonious integration of body, mind, and spirit. Chronic fatigue and emotional tension often signal energetic misalignment long before physical symptoms appear. Tarot acts as a gentle contemplative aid to uncover stress patterns and emotional exhaustion.",
      "Our 7 Chakras Spread (7 cards) and Holistic Wellness Spread (4 cards) illuminate energy bottlenecks, mental overload, and nourishing self-care habits.",
      "Vital Medical Disclaimer: Tarot readings are strictly reflective and spiritual tools. They never replace professional medical diagnosis, psychiatric evaluation, or licensed clinical treatment."
    ],
    "faqsEn": [
      {
        "question": "Can tarot diagnose specific physical illnesses?",
        "answer": "No. Tarot diagnoses emotional and psychological patterns. Always consult a certified physician for physical health concerns."
      },
      {
        "question": "How can tarot assist with stress and anxiety?",
        "answer": "By exposing the subconscious fears driving your anxiety, allowing you to prioritize self-compassion, rest, and healthy emotional boundaries."
      }
    ]
  },
  "family": {
    "seoTitleEn": "Family Tarot Spreads: Home Harmony and Relationship Healing",
    "metaDescriptionEn": "Free family and entourage tarot spreads. Resolve household conflicts, bridge generational gaps, and foster empathy and warmth at home.",
    "titleEn": "Family Tarot Spreads",
    "headingEn": "Family and Domestic Harmony Spreads",
    "taglineEn": "Bridge generational misunderstandings, heal old domestic tensions, and rebuild trust.",
    "editorialIntroEn": [
      "The family circle forms our foundational emotional bedrock, yet it is also where deep expectations and generational friction most easily collide. Tarot provides a neutral, compassionate lens to view domestic dynamics without reactive judgment.",
      "The Family & Entourage Spread (5 cards) illuminates your personal role, the collective household climate, unspoken grievances, and constructive steps toward reconciliation.",
      "Family Reading Practice: Approach the cards with active empathy. The spread highlights where forgiveness and clear, non-violent communication can restore domestic peace."
    ],
    "faqsEn": [
      {
        "question": "Can this spread be used for colleagues or close social circles?",
        "answer": "Yes. The archetype of 'entourage' applies equally to immediate family, close teams, and intimate social circles where mutual trust is paramount."
      },
      {
        "question": "How does tarot help when household members are in open conflict?",
        "answer": "It identifies the underlying emotional wounds each person is defending, suggesting who can take the first step to de-escalate tension."
      }
    ]
  },
  "study": {
    "seoTitleEn": "Academic & Exam Tarot Spreads: Focus, Prep, and Success",
    "metaDescriptionEn": "Free academic and examination tarot spreads. Assess study discipline, mental focus, test readiness, and scholarship prospects with 1909 tarot.",
    "titleEn": "Academic Tarot Spreads",
    "headingEn": "Academic and Examination Spreads",
    "taglineEn": "Calm test anxiety, pinpoint academic blind spots, and sharpen intellectual stamina.",
    "editorialIntroEn": [
      "Preparing for critical examinations, university admissions, or professional certifications often evokes heavy performance anxiety. The 1909 Rider-Waite tarot serves as a focused study audit, evaluating concentration, preparation stamina, and conceptual blind spots.",
      "Our Academic & Examination Spread (4 cards) evaluates your current preparedness, core cognitive strengths, potential distractions, and exam day performance trajectory.",
      "Academic Reading Mindset: The cards do not study for you. Diligent revision, active recall, and restful sleep remain the irreplaceable keys to academic success."
    ],
    "faqsEn": [
      {
        "question": "If the cards predict exam success, can I relax my studying?",
        "answer": "Absolutely not. The cards reflect the positive trajectory created by your present diligence. Slackening effort will immediately alter the final outcome."
      },
      {
        "question": "When is the optimal time to consult tarot about an exam?",
        "answer": "Consult the cards 1 to 2 weeks before test day to review revision strategy and adjust focus where needed."
      }
    ]
  }
};
