import fs from "node:fs";
import path from "node:path";
import { DECK } from "../src/data/cards";

const targetPath = path.resolve(process.cwd(), "src/data/cards/summary.ts");

const summaries = DECK.map((card) => ({
  id: card.id,
  name: card.nameTh,
  nameTh: card.nameTh,
  nameEn: card.nameEn,
  image: card.image,
  arcana: card.arcana,
  suit: card.suit,
  number: card.number,
  element: card.element,
  astrology: card.astrology,
  keywords: {
    upright: card.keywords.upright,
    reversed: card.keywords.reversed,
  },
}));

const content = `// Auto-generated by scripts/generate-card-summary.ts — DO NOT EDIT DIRECTLY
// Lightweight card metadata (no visual-lore, no 5D long interpretations)
// Saves bundle weight when client components only need basic card info

export interface CardSummary {
  id: string;
  name: string;
  nameTh: string;
  nameEn: string;
  image: string;
  arcana: "major" | "minor";
  suit: "wands" | "cups" | "swords" | "pentacles" | null;
  number: number;
  element: string;
  astrology: string;
  keywords: { upright: string[]; reversed: string[] };
}

export const CARD_SUMMARIES: readonly CardSummary[] = ${JSON.stringify(summaries, null, 2)} as const;

const BY_ID = new Map<string, CardSummary>(CARD_SUMMARIES.map((c) => [c.id, c]));

/**
 * ดึงข้อมูลสรุปไพ่ตาม id
 * กฎเหล็กข้อ 14 (Zero Fabricated Cards Policy): คืน undefined เมื่อหาไม่เจอ ห้ามกุไพ่มาแทนเด็ดขาด
 */
export function cardSummaryById(id?: string | null): CardSummary | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

/**
 * ดึงข้อมูลสรุปไพ่ตามลำดับ index (0-77)
 * กฎเหล็กข้อ 14 (Zero Fabricated Cards Policy): คืน undefined เมื่อเกินขอบเขต ห้ามกุไพ่มาแทนเด็ดขาด
 */
export function cardSummaryByIndex(index?: number | null): CardSummary | undefined {
  if (typeof index !== "number" || index < 0 || index >= CARD_SUMMARIES.length) {
    return undefined;
  }
  return CARD_SUMMARIES[index];
}
`;

fs.writeFileSync(targetPath, content, "utf-8");
console.log(`Generated ${summaries.length} card summaries -> ${targetPath} (${Math.round(content.length / 1024)} KB)`);
