/**
 * ภาพไพ่ 1909 Rider-Waite (กฎเหล็กข้อ 5) — อ่านตรงจาก `public/cards/w512b` ของเว็บ ไม่มีสำเนาในแอป
 * (Metro `watchFolders` ชี้ไว้ที่ metro.config.js)
 *
 * ต้องเขียนเป็น `require` ตัวอักษรตรง ๆ เพราะ Metro รวมภาพตอนบิลด์ ใช้ template string ไม่ได้
 * 78 ใบ = major 22 + 4 ดอก × 14 ตรงกับ id ใน `src/data/cards`
 * ด่าน `__tests__/card-images.test.ts` ตรวจว่าครบและตรงกับสำรับของเว็บ
 */
import type { ImageSourcePropType } from "react-native";

export const CARD_IMAGES: Record<string, ImageSourcePropType> = {
  "major-00": require("../../public/cards/w512b/major-00.webp"),
  "major-01": require("../../public/cards/w512b/major-01.webp"),
  "major-02": require("../../public/cards/w512b/major-02.webp"),
  "major-03": require("../../public/cards/w512b/major-03.webp"),
  "major-04": require("../../public/cards/w512b/major-04.webp"),
  "major-05": require("../../public/cards/w512b/major-05.webp"),
  "major-06": require("../../public/cards/w512b/major-06.webp"),
  "major-07": require("../../public/cards/w512b/major-07.webp"),
  "major-08": require("../../public/cards/w512b/major-08.webp"),
  "major-09": require("../../public/cards/w512b/major-09.webp"),
  "major-10": require("../../public/cards/w512b/major-10.webp"),
  "major-11": require("../../public/cards/w512b/major-11.webp"),
  "major-12": require("../../public/cards/w512b/major-12.webp"),
  "major-13": require("../../public/cards/w512b/major-13.webp"),
  "major-14": require("../../public/cards/w512b/major-14.webp"),
  "major-15": require("../../public/cards/w512b/major-15.webp"),
  "major-16": require("../../public/cards/w512b/major-16.webp"),
  "major-17": require("../../public/cards/w512b/major-17.webp"),
  "major-18": require("../../public/cards/w512b/major-18.webp"),
  "major-19": require("../../public/cards/w512b/major-19.webp"),
  "major-20": require("../../public/cards/w512b/major-20.webp"),
  "major-21": require("../../public/cards/w512b/major-21.webp"),
  "wands-01": require("../../public/cards/w512b/wands-01.webp"),
  "wands-02": require("../../public/cards/w512b/wands-02.webp"),
  "wands-03": require("../../public/cards/w512b/wands-03.webp"),
  "wands-04": require("../../public/cards/w512b/wands-04.webp"),
  "wands-05": require("../../public/cards/w512b/wands-05.webp"),
  "wands-06": require("../../public/cards/w512b/wands-06.webp"),
  "wands-07": require("../../public/cards/w512b/wands-07.webp"),
  "wands-08": require("../../public/cards/w512b/wands-08.webp"),
  "wands-09": require("../../public/cards/w512b/wands-09.webp"),
  "wands-10": require("../../public/cards/w512b/wands-10.webp"),
  "wands-11": require("../../public/cards/w512b/wands-11.webp"),
  "wands-12": require("../../public/cards/w512b/wands-12.webp"),
  "wands-13": require("../../public/cards/w512b/wands-13.webp"),
  "wands-14": require("../../public/cards/w512b/wands-14.webp"),
  "cups-01": require("../../public/cards/w512b/cups-01.webp"),
  "cups-02": require("../../public/cards/w512b/cups-02.webp"),
  "cups-03": require("../../public/cards/w512b/cups-03.webp"),
  "cups-04": require("../../public/cards/w512b/cups-04.webp"),
  "cups-05": require("../../public/cards/w512b/cups-05.webp"),
  "cups-06": require("../../public/cards/w512b/cups-06.webp"),
  "cups-07": require("../../public/cards/w512b/cups-07.webp"),
  "cups-08": require("../../public/cards/w512b/cups-08.webp"),
  "cups-09": require("../../public/cards/w512b/cups-09.webp"),
  "cups-10": require("../../public/cards/w512b/cups-10.webp"),
  "cups-11": require("../../public/cards/w512b/cups-11.webp"),
  "cups-12": require("../../public/cards/w512b/cups-12.webp"),
  "cups-13": require("../../public/cards/w512b/cups-13.webp"),
  "cups-14": require("../../public/cards/w512b/cups-14.webp"),
  "swords-01": require("../../public/cards/w512b/swords-01.webp"),
  "swords-02": require("../../public/cards/w512b/swords-02.webp"),
  "swords-03": require("../../public/cards/w512b/swords-03.webp"),
  "swords-04": require("../../public/cards/w512b/swords-04.webp"),
  "swords-05": require("../../public/cards/w512b/swords-05.webp"),
  "swords-06": require("../../public/cards/w512b/swords-06.webp"),
  "swords-07": require("../../public/cards/w512b/swords-07.webp"),
  "swords-08": require("../../public/cards/w512b/swords-08.webp"),
  "swords-09": require("../../public/cards/w512b/swords-09.webp"),
  "swords-10": require("../../public/cards/w512b/swords-10.webp"),
  "swords-11": require("../../public/cards/w512b/swords-11.webp"),
  "swords-12": require("../../public/cards/w512b/swords-12.webp"),
  "swords-13": require("../../public/cards/w512b/swords-13.webp"),
  "swords-14": require("../../public/cards/w512b/swords-14.webp"),
  "pentacles-01": require("../../public/cards/w512b/pentacles-01.webp"),
  "pentacles-02": require("../../public/cards/w512b/pentacles-02.webp"),
  "pentacles-03": require("../../public/cards/w512b/pentacles-03.webp"),
  "pentacles-04": require("../../public/cards/w512b/pentacles-04.webp"),
  "pentacles-05": require("../../public/cards/w512b/pentacles-05.webp"),
  "pentacles-06": require("../../public/cards/w512b/pentacles-06.webp"),
  "pentacles-07": require("../../public/cards/w512b/pentacles-07.webp"),
  "pentacles-08": require("../../public/cards/w512b/pentacles-08.webp"),
  "pentacles-09": require("../../public/cards/w512b/pentacles-09.webp"),
  "pentacles-10": require("../../public/cards/w512b/pentacles-10.webp"),
  "pentacles-11": require("../../public/cards/w512b/pentacles-11.webp"),
  "pentacles-12": require("../../public/cards/w512b/pentacles-12.webp"),
  "pentacles-13": require("../../public/cards/w512b/pentacles-13.webp"),
  "pentacles-14": require("../../public/cards/w512b/pentacles-14.webp"),
};
